<?php
include('../redirect.inc.php');
htmlHead();
topLinks();
?>
            <div class="help"> 
					   <p>For sending files to a dedicated server, Postlet is possibly one of the simplest methods.  Assuming that the website that you're viewing has set up Postlet correctly, then there are just a few simple steps for you to upload your files.</p><ul><li>Simply press the "Add" button, which will popup a file selection box.  This should mimic the file selection box of your chosen operating system, so simply select files in the way that you're used to.  Multiple files can be selected (usually using the "Ctrl" or "Apple/Command" key), however they will need to be in the same directory.  Directories can also be selected, which will in turn select all the files that are within that directory (and not files in sub-directories).</li><li>If you select files that you didn't intend to, they can be removed simply by clicking on the file in the table, and then clicking the remove button.  Again, multiple files can be selected.</li><li>Once happy with your choices, the "Upload" button should be clicked.  This will start the transfer of files from your computer, to the destination computer.  It is essential that you DO NOT refresh your browser, or browse to a different page during this process.  If you do, file upload will be terminated.</li><li>Once file upload is complete, a "Finished" message will apear above the progress bar, and depending on how Postlet has been configured, your webpage may refresh, or you may get taken to a different page.</li></ul><p>It's as simple as that.  If you're still having difficulty after these instructions, then please contact the administrator of the website you're viewing, or even post a message to the <a href="http://sourceforge.net/forum/?group_id=136812">Postlet forums</a>.</p><p>For users behind a proxy server, you need to ensure that Java is correctly set up on your machine.</p><p>To set the proxy server for your JRE, assuming you're using the SUN JRE, then do the following steps:</p><ul><li>Open the JRE control panel.  On windows this is located in the system control panel under Java (Start -> Control Panel -> Java - If this isn't visible, ensure you're using "Classic View", and not "Category View").  On Linux, this can be located by using the output of $ which java .  This will likely point (after symbolic links) to something like /usr/lib/jvm/jre-1.5.0-sun/bin/java .  The ControlPanel can be executed by substituting java on the end of this with ControlPanel .</li><li>Click the "General" tab, and then click the "Network Settings..." button.  Enter the proxy settings as stipulated by your local systen administrator</li><li>Restart your web browser.</li><li>Postlet will now use the proxy connection settings that you have specified.</li></ul><p>For users of other JREs, including Mac users, please refer to the supplier of your JRE for changing the above settings.</p>
                    </div>
<?php
htmlFooter();
